### ISSUE TITLE
Too many KPIs break layout

### ISSUE THREAD

**Issue by peol** [qlik-oss/core-experimenter#2]
When running this project on a smaller screen everything kinda breaks:

<img width="1391" alt="screen shot 2018-09-13 at 7 26 05 pm" src="https://user-images.githubusercontent.com/83221/45504730-f050d800-b78a-11e8-9c9c-6b074eeae2b8.png">

**Comment by sublibra** [comment]
_As of 1 July 2020, Qlik Core is no longer available to new customers. No further maintenance will be done in this repository._
